#!/usr/bin/env python3
"""Generate the loud-failure overrides of TCppInterOpInterpreter from ROOT's own
TInterpreter.h.

Every pure virtual that is not implemented by hand in TCppInterOpInterpreter.cxx
gets an override that fails unambiguously. Nothing returns a plausible-looking
default: the project rules forbid a ROOT operation that silently does nothing,
and an interpreter that answered "no such class" to every question would be
exactly that.

The list is generated from the pinned header rather than maintained by hand, so
it cannot drift from the TInterpreter ROOT actually calls.

Usage: gen_fatal.py <TInterpreter.h> <implemented-names-file> > fatal_methods.inc
"""
import re
import sys


def parse(hdr_path):
    src = open(hdr_path, encoding="utf-8").read()
    src = re.sub(r"//[^\n]*", "", src)
    src = re.sub(r"/\*.*?\*/", "", src, flags=re.S)
    decls = []
    for m in re.finditer(r"([^;{}]*?)=\s*0\s*;", src, flags=re.S):
        d = " ".join(m.group(1).split())
        if "(" not in d or d.startswith("#"):
            continue
        d = re.sub(r"^\s*(public|protected|private)\s*:\s*", "", d)
        d = re.sub(r"^virtual\s+", "", d)
        decls.append(d)
    return decls


def split_ret_name_args(d):
    i = d.index("(")
    head, rest = d[:i].strip(), d[i:]
    depth = 0
    for j, c in enumerate(rest):
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
            if depth == 0:
                args, tail = rest[1:j], rest[j + 1:].strip()
                break
    # type and name are not always separated, e.g. "ClassInfo_t*ClassInfo_Factory"
    m2 = re.search(r"([A-Za-z_~]\w*)\s*$", head)
    name = m2.group(1)
    ret = head[:m2.start(1)].strip()
    return ret, name, args, tail.replace("override", "").strip()


def strip_defaults(args):
    out, depth, cur = [], 0, ""
    for c in args:
        if c in "(<[":
            depth += 1
        elif c in ")>]":
            depth -= 1
        if c == "," and depth == 0:
            out.append(cur)
            cur = ""
        else:
            cur += c
    if cur.strip():
        out.append(cur)
    return ", ".join(re.sub(r"=\s*[^,]+$", "", a).strip() for a in out)


def fail_body(ret, name):
    """Never return. rkUnsupported is [[noreturn]], so no value is invented."""
    return 'rkUnsupported("%s");' % name


def main():
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <TInterpreter.h> <implemented-names-file>", file=sys.stderr)
        return 1
    hdr, impl_path = sys.argv[1], sys.argv[2]
    implemented = {
        line.strip()
        for line in open(impl_path, encoding="utf-8")
        if line.strip() and not line.startswith("#")
    }

    print("// GENERATED by gen_fatal.py from ROOT's own TInterpreter.h -- do not edit.")
    print("// Every service below is NOT implemented and fails loudly when called.")
    seen, skipped = set(), set()
    for d in parse(hdr):
        try:
            ret, name, args, tail = split_ret_name_args(d)
        except Exception:
            print("// UNPARSED: " + d, file=sys.stderr)
            continue
        if name.startswith("~"):
            continue
        if name in implemented:
            skipped.add(name)
            continue
        args_nd = strip_defaults(args)
        const = " const" if re.search(r"\bconst\b", tail.split("=")[0]) else ""
        key = (name, args_nd, const)
        if key in seen:
            continue
        seen.add(key)
        print("   %s %s(%s)%s override { %s }" % (ret, name, args_nd, const, fail_body(ret, name)))

    missing = implemented - skipped
    if missing:
        print(f"gen_fatal: FATAL these names are not pure virtuals in {hdr}: {sorted(missing)}",
              file=sys.stderr)
        return 1
    print(f"// unimplemented: {len(seen)}; implemented by hand: {len(skipped)}")
    print(f"gen_fatal: {len(seen)} loud-failure overrides, {len(skipped)} implemented by hand",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
