#!/usr/bin/env bash
# G4/G5 interpreter probe (wasm/NEXT.md's next objective).
#
# Claim under test: can the same prebuilt xeus-cpp-lite / CppInterOp
# in-browser interpreter that G7 proved (Clang-Repl under the hood) construct
# a genuine ROOT TH1D and run Fill/GetEntries/GetBinContent/Integral/GetMean
# -- with NO rootcling-generated dictionary anywhere in this page's
# toolchain, and NO hand-written Class()/Streamer()/stub/reimplemented
# histogram code -- given the real, unmodified ROOT headers mounted?
#
# This is a probe, not a gate: it never prints "G5 PASS". It exits 0
# whenever it produces evidence (resolved OR blocked) and non-zero only if
# the harness itself fails (the falsifiability control also fails, or a
# hard infrastructure error prevents any evidence being collected).
#
# Reuses G7's proven machinery unmodified: fetch-xcpp-toolchain.sh,
# drive.mjs, g2/rconfigure.cmake, and (with one backwards-compatible extra-
# args edit) g7/build_headers.py. Only the page and the header/payload
# subtree list differ.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../../../.." >/dev/null 2>&1 && pwd -P)"
TOOLCHAIN_DIR="${REPO_ROOT}/wasm/toolchain"
G2_DIR="${REPO_ROOT}/wasm/gates/g2"
G4_DIR="${REPO_ROOT}/wasm/gates/g4"
G7_DIR="${REPO_ROOT}/wasm/gates/g7"
BUILD_DIR="${REPO_ROOT}/wasm/build/g4-interpreter-probe"
EXPECTED_FILE="${G4_DIR}/expected.txt"

gate_fail() {
  echo "PROBE FAIL: $*" >&2
  exit 1
}

echo "==> [a] activating pinned Emscripten and ROOT source"
bash "${TOOLCHAIN_DIR}/fetch-root-src.sh" || gate_fail "could not fetch verified ROOT source"
# shellcheck source=../../../toolchain/root-src.env
. "${TOOLCHAIN_DIR}/root-src.env"
ROOT_SOURCE="${ROOT_WASM_TOOLS:-$HOME/.root-kata-wasm}/src/root-${ROOT_VERSION}"
if ! . "${TOOLCHAIN_DIR}/activate.sh"; then
  gate_fail "could not activate pinned Emscripten"
fi
command -v em++ >/dev/null 2>&1 || gate_fail "em++ not on PATH"
command -v cmake >/dev/null 2>&1 || gate_fail "cmake not found"
command -v node >/dev/null 2>&1 || gate_fail "node not found"
command -v chromium >/dev/null 2>&1 || gate_fail "chromium not found"
command -v python3 >/dev/null 2>&1 || gate_fail "python3 not found"
echo "    ROOT source: ${ROOT_SOURCE} (pinned ${ROOT_VERSION})"

echo "==> [b] fetching pinned xeus-cpp-lite / CppInterOp wasm toolchain (same pin as G7)"
XCPP_STAGE_DIR="$(bash "${G7_DIR}/fetch-xcpp-toolchain.sh" | tail -1)" \
  || gate_fail "could not fetch xeus-cpp-lite wasm toolchain"
for f in xcpp.js xcpp.wasm xcpp.data libxeus.so libclangCppInterOp.so; do
  [ -f "${XCPP_STAGE_DIR}/${f}" ] || gate_fail "missing staged toolchain file: ${f}"
done

echo "==> [c] generating RConfigure.h against the pinned em++ (same template G2/G7 use)"
rm -rf "${BUILD_DIR}"
mkdir -p "${BUILD_DIR}/web"
cmake -DROOT_SOURCE="${ROOT_SOURCE}" -DOUTPUT_HEADER="${BUILD_DIR}/RConfigure.h" \
  -DCXX="$(command -v em++)" -P "${G2_DIR}/rconfigure.cmake" \
  || gate_fail "RConfigure.h generation against em++ failed"
[ -s "${BUILD_DIR}/RConfigure.h" ] || gate_fail "RConfigure.h generation produced an empty file"

echo "==> [d] packaging ROOT headers (G7's four subtrees + TH1D's transitive closure) and payloads"
python3 "${G7_DIR}/build_headers.py" "${ROOT_SOURCE}" "${BUILD_DIR}/RConfigure.h" "${BUILD_DIR}/web/headers.js" \
  hist/hist/inc core/cont/inc core/meta/inc math/matrix/inc io/io/inc core/thread/inc core/clib/inc \
  || gate_fail "header packaging failed"

python3 - "${G2_DIR}/genvector.cpp" "${G4_DIR}/th1d.cpp" "${ROOT_SOURCE}/hist/hist/src/TH1.cxx" "${BUILD_DIR}/web/payload.js" <<'PY'
import json
import sys

genvector_path, th1d_path, th1cxx_path, out_path = sys.argv[1:5]

with open(genvector_path, encoding="utf-8") as f:
    control_src = f.read()
with open(th1d_path, encoding="utf-8") as f:
    probe_src = f.read()
with open(th1cxx_path, encoding="utf-8") as f:
    th1cxx_src = f.read()

with open(out_path, "w", encoding="utf-8") as f:
    f.write("// Generated by wasm/gates/g4/interpreter-probe/probe.sh -- do not edit by hand.\n")
    f.write("window.__PROBE_SRC__ = "); json.dump(probe_src, f); f.write(";\n")
    f.write("window.__CONTROL_SRC__ = "); json.dump(control_src, f); f.write(";\n")
    f.write("window.__TH1_CXX_SRC__ = "); json.dump(th1cxx_src, f); f.write(";\n")

print(f"payload: probe={len(probe_src)}B control={len(control_src)}B TH1.cxx={len(th1cxx_src)}B", file=sys.stderr)
PY

cp "${XCPP_STAGE_DIR}/xcpp.js" "${XCPP_STAGE_DIR}/xcpp.wasm" "${XCPP_STAGE_DIR}/xcpp.data" \
   "${XCPP_STAGE_DIR}/libxeus.so" "${XCPP_STAGE_DIR}/libclangCppInterOp.so" "${BUILD_DIR}/web/"
cp "${SCRIPT_DIR}/page/index.html" "${BUILD_DIR}/web/index.html"

HEADER_FILE_COUNT="$(python3 -c "
text = open('${BUILD_DIR}/web/headers.js', encoding='utf-8').read()
# crude but sufficient: count top-level '/rootsrc/' keys
print(text.count('\"/rootsrc/'))
")"
HEADER_BYTES="$(stat -c '%s' "${BUILD_DIR}/web/headers.js")"
echo "    headers.js: ${HEADER_FILE_COUNT} files, ${HEADER_BYTES} bytes (vs G7's default 4-subtree set)"

echo "==> [e] serving the static web root and driving headless Chromium"
port="$(python3 -c 'import socket
s = socket.socket()
s.bind(("127.0.0.1", 0))
print(s.getsockname()[1])
s.close()')"
(cd "${BUILD_DIR}/web" && exec python3 -m http.server "${port}" --bind 127.0.0.1) \
  > "${BUILD_DIR}/http_server.log" 2>&1 &
server_pid=$!
cleanup_probe() { kill "${server_pid}" >/dev/null 2>&1 || true; wait "${server_pid}" 2>/dev/null || true; }
trap cleanup_probe EXIT

ready=0
for _ in $(seq 1 50); do
  if curl -s -o /dev/null "http://127.0.0.1:${port}/index.html"; then
    ready=1
    break
  fi
  sleep 0.1
done
[ "${ready}" -eq 1 ] || gate_fail "local HTTP server on port ${port} did not come up"

echo "==> [f] driving the control payload (harness sanity: same enlarged include set, proven G2 program)"
node "${G7_DIR}/drive.mjs" "http://127.0.0.1:${port}/index.html?variant=control" "PROBE-DONE" 300000 \
  "${BUILD_DIR}/chrome-profile-control" > "${BUILD_DIR}/control_result.json" 2> "${BUILD_DIR}/control_drive.log" \
  || { cat "${BUILD_DIR}/control_drive.log" >&2; gate_fail "browser driver failed on the control payload"; }

CONTROL_OK="$(python3 -c "
import json
r = json.load(open('${BUILD_DIR}/control_result.json'))
cells = json.loads(r['output'] or '[]')
ok = (not r['timedOut']) and any(c['id']=='ctl-run' and c['status']=='ok' for c in cells)
print('yes' if ok else 'no')
")"
if [ "${CONTROL_OK}" != "yes" ]; then
  cat "${BUILD_DIR}/control_result.json" >&2
  gate_fail "control payload did not succeed under the enlarged include set -- harness itself is broken, result says nothing about TH1D"
fi
echo "    control: PASS (harness+enlarged-includes verified sound)"

echo "==> [g] driving the probe payload (genuine wasm/gates/g4/th1d.cpp, interpreted, not statically linked)"
probe_start_ms="$(date +%s%3N)"
node "${G7_DIR}/drive.mjs" "http://127.0.0.1:${port}/index.html?variant=probe" "PROBE-DONE" 300000 \
  "${BUILD_DIR}/chrome-profile-probe" > "${BUILD_DIR}/probe_result.json" 2> "${BUILD_DIR}/probe_drive.log" \
  || { cat "${BUILD_DIR}/probe_drive.log" >&2; gate_fail "browser driver failed on the probe payload"; }
probe_end_ms="$(date +%s%3N)"
echo "    probe wall-clock: $(( probe_end_ms - probe_start_ms )) ms"

CLASSIFICATION="$(python3 - "${BUILD_DIR}/probe_result.json" "${EXPECTED_FILE}" "${BUILD_DIR}" <<'PY'
import json
import sys

result_path, expected_path, build_dir = sys.argv[1:4]
r = json.load(open(result_path, encoding="utf-8"))
if r["timedOut"]:
    print("HARNESS-FAIL: probe did not reach PROBE-DONE within timeout")
    sys.exit(0)

cells = {c["id"]: c for c in json.loads(r["output"] or "[]")}
c1 = cells.get("c1-include")
c2 = cells.get("c2-define")
c3 = cells.get("c3-run")

def is_symbol_wall(diag):
    d = diag or ""
    return ("cannot resolve symbol" in d) or ("Dynamic linking error" in d) or ("undefined symbol" in d)

if not c1 or c1["status"] != "ok":
    diag = (c1 or {}).get("diag", "")
    label = "BLOCKED-AT-SYMBOL" if is_symbol_wall(diag) else "BLOCKED-AT-PARSE"
    note = ("interpreter fails resolving a symbol while incrementally JITting `#include <TH1D.h>` "
            "itself -- the same missing-Core-symbol wall as G4's static link, just surfaced one "
            "step earlier (at header-load time, not at main()-call time)") if label == "BLOCKED-AT-SYMBOL" \
           else "missing/unparseable header content"
    print(f"{label}: `#include <TH1D.h>` failed ({note})")
    print("--- c1-include diag ---")
    print(diag)
    sys.exit(0)

if not c2 or c2["status"] != "ok":
    diag = (c2 or {}).get("diag", "")
    label = "BLOCKED-AT-SYMBOL" if is_symbol_wall(diag) else "BLOCKED-AT-PARSE"
    print(f"{label}: th1d.cpp translation unit failed after TH1D.h parsed alone")
    print("--- c2-define diag ---")
    print(diag)
    sys.exit(0)

if not c3 or c3["status"] != "ok":
    print("BLOCKED-AT-SYMBOL: TH1D.h and th1d.cpp parsed, but `main();` failed to run")
    print("--- c3-run diag ---")
    print((c3 or {}).get("diag", ""))
    sys.exit(0)

expected = open(expected_path, encoding="utf-8").read().strip()
actual = c3["stdout"].strip()
with open(f"{build_dir}/probe_stdout.txt", "w", encoding="utf-8") as f:
    f.write(c3["stdout"])
if actual == expected:
    print("RESOLVED: main() ran and stdout matches expected.txt byte-for-byte")
    print(f"  expected: {expected!r}")
    print(f"  actual:   {actual!r}")
else:
    print("BLOCKED-AT-SYMBOL: main() reported status=ok but stdout does not match expected.txt")
    print(f"  expected: {expected!r}")
    print(f"  actual:   {actual!r}")
    print(f"  c3 diag:  {c3.get('diag','')!r}")
PY
)"
echo "${CLASSIFICATION}" | tee "${BUILD_DIR}/classification.txt"

FIRST_LINE="$(echo "${CLASSIFICATION}" | head -1)"

if echo "${FIRST_LINE}" | grep -q '^HARNESS-FAIL'; then
  gate_fail "probe harness failed to complete -- no evidence collected"
fi

if echo "${FIRST_LINE}" | grep -q '^BLOCKED-AT-SYMBOL'; then
  echo "==> [h] BLOCKED-AT-SYMBOL: bounded conditional retry feeding genuine upstream TH1.cxx before main()"
  node "${G7_DIR}/drive.mjs" "http://127.0.0.1:${port}/index.html?variant=symbol-retry" "PROBE-DONE" 300000 \
    "${BUILD_DIR}/chrome-profile-retry" > "${BUILD_DIR}/retry_result.json" 2> "${BUILD_DIR}/retry_drive.log" \
    || { cat "${BUILD_DIR}/retry_drive.log" >&2; echo "    retry harness itself failed; not chasing further (bounded to one attempt)"; }
  if [ -s "${BUILD_DIR}/retry_result.json" ]; then
    python3 -c "
import json
r = json.load(open('${BUILD_DIR}/retry_result.json'))
if r['timedOut']:
    print('    retry: timed out, no further evidence')
else:
    cells = {c['id']: c for c in json.loads(r['output'] or '[]')}
    for cid in ('c1-include', 'c1b-th1cxx', 'c2-define', 'c3-run'):
        c = cells.get(cid)
        status = c['status'] if c else 'missing'
        print(f'    retry[{cid}]: status={status}')
        if c and c['status'] != 'ok':
            print('      diag: ' + repr(c.get('diag',''))[:500])
"
  fi
fi

echo "PROBE COMPLETE (see classification above; this is evidence for a G4->G5 decision, not a gate verdict)"
exit 0
