#!/usr/bin/env python3
"""Package the staged ROOTSYS tree (include/, etc/, lib/*.rootmap, lib/*_rdict.pcm)
into a single rootsys.js the page mounts into the Emscripten virtual filesystem.

Same idea as wasm/gates/g7/build_headers.py, but for a real $ROOTSYS layout
rather than a few source subtrees: ROOT resolves its own resources by path at
runtime (TROOT::GetSharedLibDir, TEnv reading etc/system.rootrc, rootmap and
rdict.pcm next to each library), so the tree has to exist in MEMFS with the
same shape it has on disk.

The side-module .so files are deliberately NOT packed here: they are served as
static files and loaded by Emscripten's own dynamic loader (see page/index.html).

Usage: build_rootsys.py <staged-rootsys-dir> <out rootsys.js> [mount-point]
"""
import base64
import json
import os
import sys

# Kept in sync with the page's ROOTSYS. Everything under these subtrees is packed.
SUBTREES = ("include", "etc")
LIB_SUFFIXES = (".rootmap", "_rdict.pcm")


def main():
    if len(sys.argv) < 3:
        print(f"usage: {sys.argv[0]} <staged-rootsys> <out rootsys.js> [mount-point]", file=sys.stderr)
        return 1
    src, out_path = sys.argv[1], sys.argv[2]
    mount = sys.argv[3] if len(sys.argv) > 3 else "/rootsys"

    text, binary = {}, {}

    def add(full, vpath):
        with open(full, "rb") as f:
            raw = f.read()
        try:
            text[vpath] = raw.decode("utf-8")
        except UnicodeDecodeError:
            binary[vpath] = base64.b64encode(raw).decode("ascii")

    for sub in SUBTREES:
        base = os.path.join(src, sub)
        if not os.path.isdir(base):
            print(f"build_rootsys: missing {base}", file=sys.stderr)
            return 1
        for dirpath, _dirnames, filenames in os.walk(base):
            for fn in filenames:
                full = os.path.join(dirpath, fn)
                add(full, mount + "/" + os.path.relpath(full, src))

    libdir = os.path.join(src, "lib")
    for fn in sorted(os.listdir(libdir)):
        if fn.endswith(LIB_SUFFIXES):
            add(os.path.join(libdir, fn), f"{mount}/lib/{fn}")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// Generated by wasm/gates/rootweb/build_rootsys.py -- do not edit by hand.\n")
        f.write("var ROOTSYS_MOUNT = " + json.dumps(mount) + ";\n")
        f.write("var ROOTSYS_TEXT = ")
        json.dump(text, f)
        f.write(";\nvar ROOTSYS_BINARY = ")
        json.dump(binary, f)
        f.write(";\n")

    nbytes = sum(len(v.encode()) for v in text.values()) + sum(len(v) * 3 // 4 for v in binary.values())
    print(
        f"build_rootsys: wrote {out_path}: {len(text)} text + {len(binary)} binary files, {nbytes} bytes",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
