#!/usr/bin/env python3
"""Package the cells the rootweb page runs into cells.js.

Emits the unmodified source plus a deliberately-broken variant (one real
identifier typo) used for the falsifiability check -- same idea as
wasm/gates/g7/build_payload.py, but written as plain `var`s so the worker can
importScripts() it, and parameterised on the needle instead of hard-coding a
genvector-specific one.

It also packs the page's starting cell, so the editor opens on something worth
pressing Run on rather than on the gate's probe.

Usage: build_cells.py <source.cxx> <out cells.js> [welcome.cxx]
"""
import json
import re
import sys

# The broken variant renames the first plain printf call. \b does not match
# between the "f" and "p" of fprintf, so this only ever hits a standalone
# printf -- a real identifier typo, which must produce a real diagnostic.
NEEDLE_RE = re.compile(r"\bprintf\(")


def main():
    if len(sys.argv) not in (3, 4):
        print(f"usage: {sys.argv[0]} <source.cxx> <out cells.js> [welcome.cxx]", file=sys.stderr)
        return 1
    src_path, out_path = sys.argv[1:3]
    welcome_path = sys.argv[3] if len(sys.argv) > 3 else None

    with open(src_path, encoding="utf-8") as f:
        good = f.read()

    m = NEEDLE_RE.search(good)
    if not m:
        print(f"build_cells: FATAL no printf( call to corrupt in {src_path}", file=sys.stderr)
        return 1
    broken = good[:m.start()] + "printfXX(" + good[m.end():]

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// Generated by wasm/gates/rootweb/build_cells.py -- do not edit by hand.\n")
        f.write("var ROOTWEB_CELL_GOOD = ")
        json.dump(good, f)
        f.write(";\nvar ROOTWEB_CELL_BROKEN = ")
        json.dump(broken, f)
        f.write(";\nvar ROOTWEB_CELL_DEFAULT = ")
        json.dump(open(welcome_path, encoding="utf-8").read() if welcome_path else good, f)
        f.write(";\n")

        import pathlib
        repo = pathlib.Path(__file__).resolve().parents[3]
        ex_dir = repo / "src/root_kata/exercises"
        sol_dir = repo / "wasm/gates/rootkatas/solutions"
        rk_h_path = repo / "src/root_kata/include/rk.h"
        katas = []
        if ex_dir.is_dir() and sol_dir.is_dir() and rk_h_path.is_file():
            rk_h = rk_h_path.read_text(encoding="utf-8")
            for p in sorted(sol_dir.glob("*.cpp")):
                eid = p.stem
                ed = ex_dir / eid
                meta_file = ed / "exercise.json"
                if not meta_file.is_file():
                    continue
                meta = json.loads(meta_file.read_text(encoding="utf-8"))
                sol = p.read_text(encoding="utf-8")
                starter_file = ed / meta.get("starter", "solution.cpp")
                starter = starter_file.read_text(encoding="utf-8") if starter_file.is_file() else sol
                harness_file = ed / meta.get("harness", "harness.cpp")
                if not harness_file.is_file():
                    continue
                harness = harness_file.read_text(encoding="utf-8")
                sol_cell = harness.replace('#include "rk.h"', rk_h, 1).replace('#include "solution.cpp"', sol, 1)
                starter_cell = harness.replace('#include "rk.h"', rk_h, 1).replace('#include "solution.cpp"', starter, 1)
                is_blocked = eid in ("cpp-root-histogram", "cpp-root-fit-gaussian")
                katas.append({
                    "id": eid,
                    "title": meta.get("title", eid),
                    "summary": meta.get("summary", ""),
                    "difficulty": meta.get("difficulty", "Medium"),
                    "blocked": is_blocked,
                    "solution_cell": sol_cell,
                    "starter_cell": starter_cell,
                })
        f.write("var ROOTWEB_KATAS = ")
        json.dump(katas, f)
        f.write(";\n")

    print(f"build_cells: wrote {out_path} ({len(good)} good, {len(broken)} broken bytes)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
