#!/usr/bin/env python3
"""Package the ROOT header subtrees G7 needs (plus the generated RConfigure.h)
into a single headers.js the in-browser page loads and mounts into the
Emscripten virtual filesystem via FS.writeFile before compiling.

Usage: build_headers.py <root-source-dir> <rconfigure.h-path> <output headers.js> [extra-dir ...]

Extra trailing args append more ROOT-source-relative subtree dirs to the
default four (used by the g4 interpreter-probe to add hist/core/io subtrees
without touching G7's own call, which passes no extra args).
"""
import json
import os
import sys

def main():
    if len(sys.argv) < 4:
        print(f"usage: {sys.argv[0]} <root-source-dir> <rconfigure.h> <out headers.js> [extra-dir ...]", file=sys.stderr)
        return 1
    root_src, rconfigure_path, out_path = sys.argv[1:4]
    extra_dirs = sys.argv[4:]

    dirs = [
        "math/genvector/inc",
        "math/mathcore/inc",
        "core/foundation/inc",
        "core/base/inc",
    ] + extra_dirs

    mapping = {}
    for d in dirs:
        base = os.path.join(root_src, d)
        for dirpath, _dirnames, filenames in os.walk(base):
            for fn in filenames:
                full = os.path.join(dirpath, fn)
                rel = os.path.relpath(full, root_src)
                vpath = "/rootsrc/" + rel
                with open(full, "r", encoding="utf-8", errors="replace") as f:
                    mapping[vpath] = f.read()

    with open(rconfigure_path, "r", encoding="utf-8") as f:
        mapping["/rootsrc/generated/RConfigure.h"] = f.read()

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// Generated by wasm/gates/g7/build_headers.py -- do not edit by hand.\n")
        f.write("var ROOT_HEADERS = ")
        json.dump(mapping, f)
        f.write(";\n")

    total_bytes = sum(len(v.encode("utf-8")) for v in mapping.values())
    print(f"build_headers: wrote {out_path}: {len(mapping)} files, {total_bytes} header bytes", file=sys.stderr)
    return 0

if __name__ == "__main__":
    sys.exit(main())
