#!/usr/bin/env python3
"""Package the G2 genvector.cpp payload (read, never modified on disk) into
payload.js as two JS string constants: the untouched source, and a
deliberately-broken variant used only for the falsifiability check (gate G7
step 5): a single real identifier typo that must produce a genuine compiler
diagnostic, not a silent success.

Usage: build_payload.py <genvector.cpp path> <output payload.js>
"""
import json
import sys

NEEDLE = 'std::printf("pt='
REPLACEMENT = 'std::printfXX("pt='

def main():
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <genvector.cpp> <out payload.js>", file=sys.stderr)
        return 1
    src_path, out_path = sys.argv[1:3]

    with open(src_path, "r", encoding="utf-8") as f:
        good = f.read()

    if NEEDLE not in good:
        print(f"build_payload: FATAL expected substring not found in {src_path}: {NEEDLE!r}", file=sys.stderr)
        return 1
    broken = good.replace(NEEDLE, REPLACEMENT, 1)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// Generated by wasm/gates/g7/build_payload.py -- do not edit by hand.\n")
        f.write("window.__GENVECTOR_SRC_GOOD__ = ")
        json.dump(good, f)
        f.write(";\nwindow.__GENVECTOR_SRC_BROKEN__ = ")
        json.dump(broken, f)
        f.write(";\n")

    print(f"build_payload: wrote {out_path} ({len(good)} good bytes, {len(broken)} broken bytes)", file=sys.stderr)
    return 0

if __name__ == "__main__":
    sys.exit(main())
