#!/usr/bin/env python3
"""Generate a probe TInterpreter subclass from ROOT's own TInterpreter.h.

DIAGNOSTIC ONLY. Every pure virtual gets an override that logs its name and returns a
default value. The point is to enumerate which interpreter services a P0 TH1D program
actually calls -- it is not an interpreter and is never shipped (see FINDINGS.md).
"""
import re, sys

hdr = sys.argv[1]
src = open(hdr).read()
# strip comments
src = re.sub(r'//[^\n]*', '', src)
src = re.sub(r'/\*.*?\*/', '', src, flags=re.S)

# pure virtuals may wrap across lines: join then split on ';'
# Any pure-virtual declaration, without crossing a ';' or a '{' (some are declared without
# the 'virtual' keyword because they override a base declaration).
decls = []
for m in re.finditer(r'([^;{}]*?)=\s*0\s*;', src, flags=re.S):
    d = ' '.join(m.group(1).split())
    if '(' not in d or d.startswith('#'):
        continue
    d = re.sub(r'^\s*(public|protected|private)\s*:\s*', '', d)
    d = re.sub(r'^virtual\s+', '', d)
    decls.append(d)

def split_ret_name_args(d):
    i = d.index('(')
    head, rest = d[:i].strip(), d[i:]
    depth = 0
    for j, c in enumerate(rest):
        if c == '(':
            depth += 1
        elif c == ')':
            depth -= 1
            if depth == 0:
                args, tail = rest[1:j], rest[j+1:].strip()
                break
    m2 = re.search(r'([A-Za-z_~]\w*)\s*$', head)   # type and name may not be separated: "ClassInfo_t*Foo"
    name = m2.group(1)
    ret = head[:m2.start(1)].strip()
    tail = tail.replace('override', '').strip()   # some decls already say 'override'
    return ret, name, args, tail

def strip_defaults(args):
    out, depth, cur = [], 0, ''
    for c in args:
        if c in '(<[': depth += 1
        elif c in ')>]': depth -= 1
        if c == ',' and depth == 0:
            out.append(cur); cur = ''
        else:
            cur += c
    if cur.strip(): out.append(cur)
    return ', '.join(re.sub(r'=\s*[^,]+$', '', a).strip() for a in out)

def default_return(ret):
    r = ret.replace('virtual', '').strip()
    if r in ('void',): return ''
    if r.endswith('*') or r.endswith('&'): return ' return nullptr;' if r.endswith('*') else ' return *(%s*)nullptr;' % r[:-1]
    if r in ('Bool_t','bool'): return ' return kFALSE;'
    if r in ('Int_t','int','Long_t','long','Long64_t','UInt_t','size_t','Ssiz_t','ULong_t','ULong64_t','Double_t','double','Float_t','float'): return ' return 0;'
    return ' return %s();' % r

print('// GENERATED by gen_stub.py from ROOT TInterpreter.h -- diagnostic probe, do not ship.')
seen = set()
for d in decls:
    try:
        ret, name, args, tail = split_ret_name_args(d)
    except Exception:
        print('// UNPARSED: ' + d, file=sys.stderr); continue
    args_nd = strip_defaults(args)
    const = ' const' if re.search(r'\bconst\b', tail.split('=')[0]) else ''
    if name.startswith('~'): continue   # destructor is not a service
    key = (name, args_nd, const)
    if key in seen: continue
    seen.add(key)
    body = 'RKLOG("%s");%s' % (name, default_return(ret))
    print('   %s %s(%s)%s override { %s }' % (ret, name, args_nd, const, body))
print('// total overrides: %d' % len(seen), file=sys.stderr)
